service:
  port: "8080"
database:
  name: iam
  password: admin
  host: localhost
  port: "3306"
  username: root
rabbitmq:
  username: admin
  password: admin
  host: localhost
  port: "5672"
roles:
  - Owner
  - Reader
  - Contributor
permissions:
  - Create
  - Read
  - Update
  - Delete